### ISSUE TITLE
Add all Requirements in a file

### ISSUE THREAD

**Issue by ericbbraga** [thiagoolsilva/cryptography-cli#5]
It's common in python to use a file (requiriments.txt) to add all libraries used in one project / module.
I think it could be better to manage all dependencies

**Comment by thiagoolsilva** [comment]
Hi Braga, thanks for your reply. 

Só, There is two files to manage all external dependencies on project. The first one named requirements.txt and another one requirements-dev.txt that include all production and dev dependencies. 

Please check these files on module key-generator. 

Thanks my friend and If you have more improvements please let me know about it.

**Comment by thiagoolsilva** [comment]
Once the proposed files exist on project I'll close this issue.
